version: '3.8'
services:
  db:
    image: postgres:14
    container_name: event_management_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: event_management
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
